version: 2.1


jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.0
    working_directory: ~/hakadori/api
    steps:
      - checkout
        path: ~/hakadori
      - ruby/bundle-install
  
  test:
    docker:
      - image: cimg/ruby:3.1.0
      - image: image: cimg/mysql:8.0
        environment: 
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: myapp_test
          MYSQL_USER: root
    environment: 
      BUDLE_JOBS: "4"
      BUDLE_RETRY: "3"
      MYAPP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/hakadori/api
    steps: 
      - checkout: 
        pash: ~/hakadori
      - ruby/bundle-install
      - run:
          name: rails db:migrate
          command: bundle exec rails db:migrate
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: Rspec
          command: bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires: 
          - build
