version: 2.1

jobs:
  test_api:
    docker:
      - image: cimg/ruby:3.1.0
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
      - image: cimg/mysql:8.0

    working_directory: ~/hakadori/api

    steps:
      - checkout

      # restore gem from cache
      - restore_cache:
          keys:
            - gem-cache-v1-{{ checksum "~/hakadori/api/Gemfile.lock" }}
            - gem-cache-v1-
          working_directory: ~/hakadori/api

      # gem install
      - run:
          command: |
            gem install bundler
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
          working_directory: ~/hakadori/api

      - save_cache:
          key: gem-cache-v1-{{ checksum "~/hakadori/api/Gemfile.lock" }}
          paths:
            - ~/repo/backend/vendor/bundle
          working_directory: ~/hakadori/api

      # Database setup
      - run:
          command: bundle exec rails db:create
          working_directory: ~/hakadori/api
      - run:
          command: bundle exec rails db:migrate
          working_directory: ~/hakadori/api

      - run:
          name: create directory to store test results
          command: mkdir /tmp/test-results
          working_directory: ~/hakadori/api

      # run tests
      - run:
          name: RSpec
          command: |
            bundle exec rspec $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings) \
              || (printf "====== RETRYING...\n\n\n"; bundle exec rspec --only-failures)
          working_directory: ~/hakadori/api

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
      - store_artifacts:
          path: /home/circleci/repo/tmp/screenshots

workflows:
  version: 2
  test:
    jobs:
      - test_api
