# version: 2.1
# orbs:
#   ruby: circleci/ruby@1.1.2
#   node: circleci/node@2

# jobs:
#   build:
#     docker:
#       - image: circleci/ruby:3.0.3
#     working_directory: ~/hakadori/api
#     steps:
#       - checkout:
#           path: ~/hakadori/api
#       - restore_cache:
#           keys:
#             - gem-cache-v1-{{ checksum "~/hakadori/api/Gemfile.lock" }}
#           working_directory: ~/hakadori/api
#       - ruby/install-deps

#   # test:
#   #   docker:
#   #     - image: cimg/ruby:3.0.3-node
#   #     - image: circleci/mysql:8.0
#   #       environment:
#   #         MYSQL_ROOT_PASSWORD: Qunitaros10
#   #         MYSQL_DATABASE: hakadori_test
#   #         MYSQL_USER: qunitaros
#   #         MYSQL_PASSWORD: Qunitaros10
#   #   environment:
#   #     BUNDLE_JOBS: "3"
#   #     BUNDLE_RETRY: "3"
#   #     APP_DATABASE_HOST: "127.0.0.1"
#   #     RAILS_ENV: test
#   #   working_directory: ~/hakadori/api
#   #   steps:
#   #     - checkout:
#   #         path: ~/hakadori/api
#   #     - ruby/install-deps
#   #     - run:
#   #         name: MySQL が準備できるまで待機
#   #         command: |
#   #           for i in `seq 1 10`;
#   #           do
#   #             nc -z 127.0.0.1 3360 && echo Success && exit 0
#   #             echo -n .
#   #             sleep 1
#   #           done
#   #           echo Failed waiting for MySQL && exit 1
#   #     - run:
#   #         name: データベースの作成
#   #         command: bundle exec rake db:create
#   #     - run:
#   #         name: データベースのセットアップ
#   #         command: bundle exec rake db:migrate
#   #     - run:
#   #         name: test
#   #         command: bundle exec rspec

#   # deploy:
#   #   docker:
#   #     - image: cimg/ruby:3.0.2-node
#   #   working_directory: ~/hakadori/api
#   #   steps:
#   #     - checkout:
#   #        path: ~/hakadori/api
#   #     - ruby/install-deps
#   #     - add_ssh_keys:
#   #         fingerprints: 35:5a:cb:c6:0e:b3:5b:5e:48:fb:dd:99:4c:90:cb:a3
#   #     - run:
#   #         name: 自動デプロイ
#   #         command: bundle exec cap production deploy

# workflows:
#   version: 2
#   build_and_test_and_deploy:
#     jobs:
#       - build
#       # - test:
#       #     requires:
#       #       - build
#       # - deploy:
#       #     requires:
#       #       - test
#       #     filters:
#       #       branches:
#       #         only: master
version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  node: circleci/node@2

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.0
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  jobs:
    - build
